const fish = [
    {
        name: "Dragon Scale Male Betta Fish",
        image: "https://s7d2.scene7.com/is/image/PetSmart/5164011?$sclp-prd-main_large$",
        price: "9.99",
        type: ["Betta"],
        color: "red",
        communityspecies: "no",
    },
    {
        name: "Crowntail Male Betta Fish",
        image: "https://s7d2.scene7.com/is/image/PetSmart/5107695?$sclp-prd-main_large$",
        price: "7.99",
        type: ["Betta"],
        color: "blue",
        communityspecies: "no",
    },
    {
        name: "Dumbo Halfmoon Male Betta Fish",
        image: "https://s7d2.scene7.com/is/image/PetSmart/5210839?$sclp-prd-main_large$",
        price: "9.99",
        type: ["Betta"],
        color: "purple",
        communityspecies: "no",
    },
    {
        name: "Premium Butterfly Male Betta Fish",
        image: "https://s7d2.scene7.com/is/image/PetSmart/5249054?$sclp-prd-main_large$",
        price: "9.99",
        type: ["Betta"],
        color: "red",
        communityspecies: "no",
    },
    {
        name: "Comet Goldfish",
        image: "https://s7d2.scene7.com/is/image/PetSmart/4032785?$sclp-prd-main_large$",
        price: "0.36",
        type: ["Goldfish"],
        color: "orange",
        communityspecies: "yes",
    },
    {
        name: "Yellow Guppy",
        image: "https://s7d2.scene7.com/is/image/PetSmart/5015604?$sclp-prd-main_large$",
        price: "3.99",
        type: ["Marine & Freshwater"],
        color: "yellow",
        communityspecies: "yes",
    },
    {
        name: "Platinum Guppy Male",
        image: "https://s7d2.scene7.com/is/image/PetSmart/5292988?$sclp-prd-main_large$",
        price: "3.99",
        type: ["Marine & Freshwater"],
        color: "white",
        communityspecies: "yes",
    },
    {
        name: "Blue Wag Platy",
        image: "https://s7d2.scene7.com/is/image/PetSmart/1181752?$sclp-prd-main_large$",
        price: "2.99",
        type: ["Marine & Freshwater"],
        color: "blue",
        communityspecies: "yes",
    },
    {
        name: "GloFish Galactic Purple Longfin Tetra",
        image: "https://s7d2.scene7.com/is/image/PetSmart/5277074?$sclp-prd-main_large$",
        price: "11.99",
        type: ["Marine & Freshwater"],
        color: "purple",
        communityspecies: "yes",
    },
    {
        name: "Butterfly Koi",
        image: "https://s7d2.scene7.com/is/image/PetSmart/4033736?$sclp-prd-main_large$",
        price: "13.99",
        type: ["Koi"],
        color: "yellow",
        communityspecies: "yes",
    },
    {
        name: "Dalmatian Lyretail Molly",
        image: "https://s7d2.scene7.com/is/image/PetSmart/4034838?$sclp-prd-main_large$",
        price: "5.49",
        type: ["Marine & Freshwater"],
        color: "black",
        communityspecies: "yes",
    },
    {
        name: "Assorted Veil Angels",
        image: "https://s7d2.scene7.com/is/image/PetSmart/4034910?$sclp-prd-main_large$",
        price: "5.99",
        type: ["Marine & Freshwater"],
        color: "black",
        communityspecies: "yes",
    },
    {
        name: "Assorted African Cichlids",
        image: "https://s7d2.scene7.com/is/image/PetSmart/5292974?$sclp-prd-main_large$",
        price: "7.99",
        type: ["Cichlid"],
        color: "beige",
        communityspecies: "no",
    },
    {
        name: "Blood-Red Parrot Cichlid",
        image: "https://s7d2.scene7.com/is/image/PetSmart/4034863?$sclp-prd-main_large$",
        price: "19.99",
        type: ["Cichlid"],
        color: "orange",
        communityspecies: "yes",
    },
    {
        name: "Electric Yellow Labidochromis African Cichlid",
        image: "https://s7d2.scene7.com/is/image/PetSmart/4031377?$sclp-prd-main_large$",
        price: "10.99",
        type: ["Cichlid"],
        color: "yellow",
        communityspecies: "no",
    },
    {
        name: "Assorted Oranda Goldfish",
        image: "https://s7d2.scene7.com/is/image/PetSmart/5152446?$sclp-prd-main_large$",
        price: "9.99",
        type: ["Goldfish"],
        color: "white",
        communityspecies: "yes",
    },
    {
        name: "Black Moor Goldfish",
        image: "https://s7d2.scene7.com/is/image/PetSmart/4032316?$sclp-prd-main_large$",
        price: "7.99",
        type: ["Goldfish"],
        color: "black",
        communityspecies: "yes",
    },
    {
        name: "Koi Angelfish",
        image: "https://s7d2.scene7.com/is/image/PetSmart/5266408?$sclp-prd-main_large$",
        price: "12.99",
        type: ["Koi"],
        color: "black",
        communityspecies: "no",
    },
    {
        name: "Rosy Red Minnow",
        image: "https://s7d2.scene7.com/is/image/PetSmart/4032886?$sclp-prd-main_large$",
        price: "0.20",
        type: ["Marine & Freshwater"],
        color: "pink",
        communityspecies: "yes",
    },
    {
        name: "Plecostomus",
        image: "https://s7d2.scene7.com/is/image/PetSmart/4032058?$sclp-prd-main_large$",
        price: "6.99",
        type: ["Marine & Freshwater"],
        color: "black",
        communityspecies: "no",
    }
]

export {fish};